# Generated by Django 5.1.4 on 2024-12-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masrof', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masrof',
            options={'managed': True, 'ordering': ['date'], 'verbose_name': 'مصاريف', 'verbose_name_plural': 'مصاريف'},
        ),
        migrations.AlterField(
            model_name='masrof',
            name='day',
            field=models.CharField(max_length=50, verbose_name='يوم'),
        ),
    ]
