# Generated by Django 5.1.4 on 2024-12-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesabi',
            name='day',
            field=models.CharField(max_length=50, verbose_name='يوم'),
        ),
        migrations.AlterField(
            model_name='hesabi',
            name='month',
            field=models.CharField(blank=True, max_length=51, null=True, verbose_name=' الشهر'),
        ),
    ]
