# Generated by Django 5.1.4 on 2024-12-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yaomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, verbose_name=' اليوم')),
                ('day_date', models.DateField(verbose_name=' الموافق')),
                ('servies', models.CharField(blank=True, max_length=50, null=True, verbose_name=' الخدمه')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=' ثمنها')),
                ('rest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=' متبقى')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name=' الهاتف')),
            ],
            options={
                'verbose_name': 'دفتر اليوميه',
                'verbose_name_plural': 'دفتر اليوميه',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
