# Generated by Django 5.1.4 on 2024-12-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='العمر')),
                ('job', models.CharField(blank=True, max_length=50, null=True, verbose_name='الوظيفه')),
            ],
            options={
                'verbose_name': 'تحت التجربه',
                'verbose_name_plural': 'تحت التجربه',
            },
        ),
    ]
