# Generated by Django 5.1.4 on 2024-12-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_imageuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuser',
            name='img',
            field=models.ImageField(upload_to='img_photos', verbose_name='الصوره'),
        ),
    ]
