# Generated by Django 5.1.4 on 2024-12-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servie',
            options={'managed': True, 'ordering': ['paid_at'], 'verbose_name': 'الخدمات', 'verbose_name_plural': 'الخدمات'},
        ),
    ]
