# Generated by Django 5.1.4 on 2024-12-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manzoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name=' الكود')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name=' الكميه')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name=' الثمن')),
                ('date', models.DateField(verbose_name=' التاريخ')),
                ('img', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name=' الصوره')),
            ],
            options={
                'verbose_name': 'منظومة دعوات الافراح',
                'verbose_name_plural': 'منظومة دعوات الافراح',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
