# Generated by Django 5.1.4 on 2024-12-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_manzoma_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manzoma',
            name='img',
            field=models.ImageField(upload_to='photos', verbose_name=' الصوره'),
        ),
    ]
