# Generated by Django 5.1.4 on 2024-12-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_hesabi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masrof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msrof', models.DecimalField(decimal_places=2, max_digits=5, verbose_name=' مصروف')),
                ('name', models.CharField(max_length=50, verbose_name=' لحساب')),
                ('date', models.DateField(verbose_name=' بتاريخ')),
            ],
            options={
                'verbose_name': 'مصاريف',
                'verbose_name_plural': 'مصاريف',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
