# Generated by Django 5.1.4 on 2024-12-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_hesabi_day_masrof_day_alter_hesabi_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hesabi',
            options={'managed': True, 'ordering': ['at'], 'verbose_name': 'حسابى', 'verbose_name_plural': 'حسابى'},
        ),
        migrations.AlterModelOptions(
            name='manzoma',
            options={'managed': True, 'ordering': ['code'], 'verbose_name': 'منظومة دعوات الافراح', 'verbose_name_plural': 'منظومة دعوات الافراح'},
        ),
        migrations.AlterModelOptions(
            name='masrof',
            options={'managed': True, 'ordering': ['date'], 'verbose_name': 'مصاريف', 'verbose_name_plural': 'مصاريف'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'البضائع', 'verbose_name_plural': 'البضائع'},
        ),
        migrations.AlterModelOptions(
            name='servie',
            options={'managed': True, 'ordering': ['paid_at'], 'verbose_name': 'الخدمات', 'verbose_name_plural': 'الخدمات'},
        ),
        migrations.AlterModelOptions(
            name='yaomia',
            options={'managed': True, 'ordering': ['day_date'], 'verbose_name': 'دفتر اليوميه', 'verbose_name_plural': 'دفتر اليوميه'},
        ),
        migrations.AlterField(
            model_name='hesabi',
            name='day',
            field=models.CharField(max_length=50, verbose_name='يوم'),
        ),
        migrations.AlterField(
            model_name='hesabi',
            name='month',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name=' الشهر'),
        ),
        migrations.AlterField(
            model_name='manzoma',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=' التاريخ'),
        ),
        migrations.AlterField(
            model_name='masrof',
            name='day',
            field=models.CharField(max_length=50, verbose_name='يوم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name=' سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='yaomia',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name=' ثمنها'),
        ),
        migrations.AlterField(
            model_name='yaomia',
            name='servies',
            field=models.CharField(max_length=50, verbose_name=' الخدمه'),
        ),
    ]
